import 'package:flutter/material.dart';

import '../data/demo_transit_catalog.dart';
import '../models/location_node.dart';
import '../models/transit_route_option.dart';
import '../models/microbus_line.dart';
import '../models/trip_record.dart';
import '../models/transit_enums.dart';
import '../services/trip_manager.dart';
import '../services/trip_repository.dart';
import '../services/supabase_service.dart';

class TripPlannerController extends ChangeNotifier {
  TripPlannerController({TripManager? tripManager}) : _tripManager = tripManager ?? const TripManager() {
    loadMicrobusLines();
    loadTrainLines();
  }

  final TripManager _tripManager;
  final TripRepository _tripRepository = TripRepository();

  String _selectedOriginGovernorate = 'Cairo';
  LocationNode _selectedOriginCity = DemoTransitCatalog.defaultOrigin;
  LocationNode _selectedBenhaDestination = DemoTransitCatalog.defaultDestination;
  TripPlanResult? _latestPlan;
  List<MicrobusLine> _microbusLines = [];
  List<Map<String, dynamic>> _trainLines = [];

  LocationNode get origin => _selectedOriginCity;
  LocationNode get destination => _selectedBenhaDestination;
  TripPlanResult? get latestPlan => _latestPlan;

  String get selectedOriginGovernorate => _selectedOriginGovernorate;
  LocationNode get selectedOriginCity => _selectedOriginCity;
  LocationNode get selectedBenhaDestination => _selectedBenhaDestination;

  List<String> get governorates => DemoTransitCatalog.governorates;
  List<LocationNode> getLocationsForGovernorate(String gov) => DemoTransitCatalog.getCitiesForGovernorate(gov);
  List<LocationNode> get benhaDestinations => DemoTransitCatalog.benhaDestinations;

  List<LocationNode> get locations => DemoTransitCatalog.locations;
  List<MicrobusLine> get microbusLines => _microbusLines;
  List<Map<String, dynamic>> get trainLines => _trainLines;

  void setSelectedOriginGovernorate(String gov) {
    _selectedOriginGovernorate = gov;
    final cities = getLocationsForGovernorate(gov);
    if (cities.isNotEmpty) {
      _selectedOriginCity = cities.first;
    }
    notifyListeners();
  }

  void setSelectedOriginCity(LocationNode city) {
    _selectedOriginCity = city;
    notifyListeners();
  }

  void setSelectedBenhaDestination(LocationNode dest) {
    _selectedBenhaDestination = dest;
    notifyListeners();
  }

  Future<void> loadMicrobusLines() async {
    try {
      _microbusLines = await _tripRepository.fetchMicrobusLines();
      notifyListeners();
    } catch (e) {
      print('Error loading microbus lines: $e');
    }
  }

  Future<void> loadTrainLines() async {
    try {
      _trainLines = await _tripRepository.fetchTrainLines();
      notifyListeners();
    } catch (e) {
      print('Error loading train lines: $e');
    }
  }

  void setOrigin(LocationNode location) {
    _selectedOriginCity = location;
    if (location.governorate != null) {
      _selectedOriginGovernorate = location.governorate!;
    }
    notifyListeners();
  }

  void setDestination(LocationNode location) {
    _selectedBenhaDestination = location;
    notifyListeners();
  }

  void swapEndpoints() {
    // Only swap if the current origin is also a valid Benha destination.
    final isOriginInBenha = benhaDestinations.any((d) => d.id == _selectedOriginCity.id);
    if (isOriginInBenha) {
      final temp = _selectedOriginCity;
      _selectedOriginCity = _selectedBenhaDestination;
      _selectedBenhaDestination = temp;
      if (_selectedOriginCity.governorate != null) {
        _selectedOriginGovernorate = _selectedOriginCity.governorate!;
      }
      notifyListeners();
    }
  }

  TripPlanResult planTrip({TripPreferences preferences = const TripPreferences(), String localeCode = 'en'}) {
    _latestPlan = _tripManager.evaluate(
      origin: _selectedOriginCity,
      destination: _selectedBenhaDestination,
      preferences: preferences,
      microbuses: _microbusLines,
      trains: _trainLines,
      localeCode: localeCode,
    );
    _saveTripToHistory();
    Future.microtask(() => notifyListeners());
    return _latestPlan!;
  }

  Future<void> _saveTripToHistory() async {
    if (_latestPlan == null) return;

    final currentUser = SupabaseService.client?.auth.currentUser;
    final trip = TripRecord(
      id: 0, // generated by database
      origin: _selectedOriginCity,
      destination: _selectedBenhaDestination,
      estimatedTime: _latestPlan!.routes.isNotEmpty ? _latestPlan!.routes.first.durationMinutes : 60,
      estimatedCost: _latestPlan!.routes.isNotEmpty ? _latestPlan!.routes.first.estimatedCost : 20.0,
      transfers: _latestPlan!.routes.isNotEmpty ? _latestPlan!.routes.first.transfers : 0,
      status: TripStatus.completed,
      createdAt: DateTime.now(),
      routes: _latestPlan!.routes.map((r) => r.title).toList(),
    );

    if (currentUser == null) {
      // For guest users, append to local memory
      DemoTransitCatalog.history.insert(0, trip);
      return;
    }

    try {
      await _tripRepository.saveTrip(trip, userId: currentUser.id);
    } catch (e) {
      print('Error saving trip in controller: $e');
    }
  }
}