create extension if not exists pgcrypto;

do $$
begin
  create type public.location_type as enum ('University', 'Hospital', 'Station', 'Hub', 'Restaurant', 'Cafe');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.trip_status as enum ('COMPLETED', 'CANCELLED', 'IN_PROGRESS');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.route_mode as enum ('TRAIN', 'MICROBUS', 'PUBLIC_BUS', 'BORDER_BUS');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  coordinates point not null,
  type public.location_type not null,
  created_at timestamptz not null default now(),
  constraint locations_name_unique unique (name)
);

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  current_location_id bigint references public.locations(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  origin_id bigint not null references public.locations(id) on delete restrict,
  dest_id bigint not null references public.locations(id) on delete restrict,
  est_time integer not null check (est_time >= 0),
  est_cost numeric(10,2) not null check (est_cost >= 0),
  transfers integer not null default 0 check (transfers >= 0),
  status public.trip_status not null default 'IN_PROGRESS',
  created_at timestamptz not null default now(),
  constraint trips_origin_dest_distinct check (origin_id <> dest_id)
);

create table if not exists public.routes (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  details text not null,
  mode public.route_mode not null,
  gmaps_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.microbuses (
  id bigint generated by default as identity primary key,
  category varchar(255) not null,
  line_no integer not null,
  route varchar(255) not null,
  fare numeric(10, 2) not null,
  created_at timestamptz not null default now()
);

create table if not exists public.trains (
  id bigint generated by default as identity primary key,
  train_no varchar(50) not null,
  type varchar(100) not null,
  type_en varchar(100) not null,
  origin varchar(100) not null,
  origin_en varchar(100) not null,
  dest varchar(100) not null,
  dest_en varchar(100) not null,
  dep_time varchar(20) not null,
  arr_benha varchar(20) not null,
  price numeric(10, 2) not null,
  duration integer not null,
  created_at timestamptz not null default now(),
  constraint trains_train_no_origin_unique unique (train_no, origin)
);

create table if not exists public.chats (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  message text not null,
  ai_response text not null,
  trip_id bigint references public.trips(id) on delete set null,
  timestamp timestamptz not null default now()
);

create index if not exists idx_locations_type on public.locations(type);
create index if not exists idx_trips_user_id on public.trips(user_id);
create index if not exists idx_trips_origin_id on public.trips(origin_id);
create index if not exists idx_trips_dest_id on public.trips(dest_id);
create index if not exists idx_trips_created_at on public.trips(created_at desc);
create index if not exists idx_routes_trip_id on public.routes(trip_id);
create index if not exists idx_chats_user_id on public.chats(user_id);
create index if not exists idx_chats_trip_id on public.chats(trip_id);
create index if not exists idx_chats_timestamp on public.chats(timestamp desc);

alter table public.locations enable row level security;
alter table public.users enable row level security;
alter table public.trips enable row level security;
alter table public.routes enable row level security;
alter table public.chats enable row level security;
alter table public.microbuses enable row level security;
alter table public.trains enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'locations' and policyname = 'locations are readable by everyone'
  ) then
    create policy "locations are readable by everyone"
      on public.locations
      for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'users' and policyname = 'users can read their profile'
  ) then
    create policy "users can read their profile"
      on public.users
      for select
      using (auth.uid() = id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'users' and policyname = 'users can update their profile'
  ) then
    create policy "users can update their profile"
      on public.users
      for update
      using (auth.uid() = id)
      with check (auth.uid() = id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'trips' and policyname = 'users manage their trips'
  ) then
    create policy "users manage their trips"
      on public.trips
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'routes' and policyname = 'routes follow trip ownership'
  ) then
    create policy "routes follow trip ownership"
      on public.routes
      for all
      using (exists (select 1 from public.trips t where t.id = trip_id and t.user_id = auth.uid()))
      with check (exists (select 1 from public.trips t where t.id = trip_id and t.user_id = auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'chats' and policyname = 'chats belong to current user'
  ) then
    create policy "chats belong to current user"
      on public.chats
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'microbuses' and policyname = 'microbuses are readable by everyone'
  ) then
    create policy "microbuses are readable by everyone"
      on public.microbuses
      for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'trains' and policyname = 'trains are readable by everyone'
  ) then
    create policy "trains are readable by everyone"
      on public.trains
      for select
      using (true);
  end if;
end $$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'full_name', new.email, 'BanHops Rider')
  )
  on conflict (id) do update
    set name = excluded.name;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();