import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'splash_title': 'BanHops',
      'splash_subtitle': 'Fast routes for smart travel',
      'choose_language': 'Please select a language',
      'arabic': 'العربية',
      'english': 'English',
      'welcome': 'Welcome to',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'home': 'Home',
      'from': 'From',
      'to': 'To',
      'get_routes': 'Get Routes',
      'popular_zones': 'Popular Zones',
      'train_lines': 'Train Lines',
      'where_are_you_coming_from': 'Where are you coming from?',
      'trip_history': 'Trip History',
      'profile': 'Profile',
      'settings': 'Settings',
      'language': 'Language',
      'apply': 'Apply',
      'current_language': 'Current Language',
      'select_destination': 'Select Destination',
      'route_details': 'Route Details',
      'transportation_options': 'Transportation Options',
      'best_match': 'BEST MATCH',
      'direct_microbus': 'Direct Microbus',
      'train_nearby': 'Train (Nearby Station)',
      'pros': 'Pros',
      'cons': 'Cons',
      'chat_assistant': 'AI Assistant',
      'smart_route': 'Smart Route to Benha',
      'completed_trips': 'Completed Trips',
      'banhops_user': 'BanHops User',
      'banhops_explorer': 'BANHOPS EXPLORER',
      'search_destination': 'Search for a destination in Benha',
      'current_location': 'Your current location',
      'cairo': 'Cairo',
      'tanta': 'Tanta',
      'mansoura': 'Mansoura',
      'minya': 'Minya',
      'new_language_applied':
          'The new language will be applied to all app screens',
      'continue': 'Continue',
      'login': 'Login',
      'register': 'Register',
      'guest_mode': 'Continue as Guest',
      'plan_trip': 'Plan Trip',
      'recommended_routes': 'Recommended Routes',
      'smart_insight': 'Smart Insight',
      'completed_trip_count': 'Completed Trips Count',
      'fastest_route': 'Fastest route?',
      'what_cost': 'What cost?',
      'nearest_station': 'Nearest station?',
      'route_summary': 'Route Summary',
      'ai_assistant': 'AI Assistant',
      'history_log': 'Historical Trip Log',
      'train_map': 'Train Lines Map',
      'smart_insight_subtitle': 'Find the best combination of train, bus, and microbus routes across Benha.',
      'swap': 'Swap',
      'view_recommended_routes_title': 'View recommended routes',
      'view_recommended_routes_subtitle': 'See the ranked route cards and AI guidance.',
      'open_ai_assistant_title': 'Open AI assistant',
      'open_ai_assistant_subtitle': 'Ask about fare, timing, or station pairing.',
      'select_governorate': 'Select Governorate',
      'select_city': 'Select City/Area',
      'select_destination_in_benha': 'Where in Benha?',
      'popular_zones_sheet_title': 'Choose your destination in Benha',
      'train_route_first': 'Rail-first route',
      'train_route_connector': 'Train + microbus connector',
      'train_segment_detail': 'Train segment from %s toward %s with a short connector if needed.',
      'combined_train_route': 'Combined Rail Route',
      'combined_train_detail': 'Take train from %s to Cairo Ramses, then transfer to a train to Benha.',
      'no_routes_available': 'No routes available',
      'try_adjusting_filters': 'Try adjusting your filters',
      'recommended': 'Recommended',
      'view_details': 'View Details →',
      'duration': 'Duration',
      'cost': 'Cost',
      'cost_2026': 'Cost (2026 Rate)',
      'transfers': 'Transfers',
      'route_plan': 'Route Plan',
      'min': 'min',
      'egp': 'EGP',
      'transfer': 'transfer',
      'transfers_plural': 'transfers',
      'your_journey': 'Your Journey',
      'step_by_step_guidance': 'Step-by-Step Guidance',
      'detailed_instructions_fallback': 'Detailed instructions will be available in the app.',
      'rating_feedback': 'Rating & Feedback',
      'average_user_rating': 'Average user rating',
      'price_estimate_disclaimer': '* Prices are estimates based on 2026 rates and may vary',
      'view_on_google_maps': 'View on Google Maps',
      'back_to_results': 'Back to Results',
      'sort_and_filter': 'Sort & Filter',
      'cheapest': 'Cheapest',
      'fastest': 'Fastest',
      'all_modes': 'All Modes',
      'microbus': 'Microbus',
      'train': 'Train',
      'public_bus': 'Public Bus',
      'border_bus': 'Border Bus',
      'transfer_point': 'Transfer Point',
      'type_university': 'University',
      'type_hospital': 'Hospital',
      'type_station': 'Station',
      'type_hub': 'Hub/Terminal',
      'type_cafe': 'Cafe',
      'type_restaurant': 'Restaurant',
      'sign_out_title': 'Sign Out',
      'sign_out_confirm': 'Are you sure you want to sign out?',
      'cancel': 'Cancel',
      'sign_out': 'Sign Out',
      'available_trains': 'Available Trains to Benha',
      'train_no': 'Train No.',
      'train_type': 'Type',
      'departure': 'Departure',
      'arrival': 'Arrival at Benha',
      'price': 'Price',
      'view_train_schedule': 'View Available Trains Schedule',
    },
    'ar': {
      'splash_title': 'بنهوبس',
      'splash_subtitle': 'طرق سريعة للسفر الذكي',
      'choose_language': 'الرجاء اختيار لغة',
      'arabic': 'العربية',
      'english': 'English',
      'welcome': 'مرحبًا بك في',
      'sign_in': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'first_name': 'الاسم الأول',
      'last_name': 'اسم العائلة',
      'confirm_password': 'تأكيد كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'dont_have_account': 'لا تملك حسابًا؟',
      'already_have_account': 'بالفعل لديك حساب؟',
      'home': 'الرئيسية',
      'from': 'من',
      'to': 'إلى',
      'get_routes': 'احصل على الطرق',
      'popular_zones': 'المناطق الشعبية',
      'train_lines': 'خطوط القطارات',
      'where_are_you_coming_from': 'من أين ستبدأ رحلتك؟',
      'trip_history': 'سجل الرحلات',
      'profile': 'الحساب',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'apply': 'تطبيق',
      'current_language': 'اللغة الحالية',
      'select_destination': 'اختر وجهتك',
      'route_details': 'تفاصيل الطريق',
      'transportation_options': 'خيارات التنقل',
      'best_match': 'أفضل اختيار',
      'direct_microbus': 'ميكروباص مباشر',
      'train_nearby': 'قطار (محطة قريبة)',
      'pros': 'الإيجابيات',
      'cons': 'السلبيات',
      'chat_assistant': 'مساعد الذكاء الاصطناعي',
      'smart_route': 'المسار الذكي إلى بنها',
      'completed_trips': 'الرحلات المكتملة',
      'banhops_user': 'مستخدم بنهوبس',
      'banhops_explorer': 'مستكشف بنهوبس',
      'search_destination': 'ابحث عن وجهة في بنها',
      'current_location': 'موقعك الحالي',
      'cairo': 'القاهرة',
      'tanta': 'طنطا',
      'mansoura': 'المنصورة',
      'minya': 'المنيا',
      'new_language_applied': 'سيتم تطبيق اللغة الجديدة على جميع الشاشات',
      'continue': 'متابعة',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'guest_mode': 'المتابعة كضيف',
      'plan_trip': 'تخطيط الرحلة',
      'recommended_routes': 'المسارات المقترحة',
      'smart_insight': 'الرؤية الذكية',
      'completed_trip_count': 'عدد الرحلات المكتملة',
      'fastest_route': 'أسرع طريق؟',
      'what_cost': 'ما التكلفة؟',
      'nearest_station': 'أقرب محطة؟',
      'route_summary': 'ملخص المسار',
      'ai_assistant': 'مساعد الذكاء الاصطناعي',
      'history_log': 'سجل الرحلات',
      'train_map': 'خريطة خطوط القطار',
      'smart_insight_subtitle': 'اعثر على أفضل توليفة من مسارات القطارات والأتوبيسات والميكروباصات عبر بنها.',
      'swap': 'تبديل',
      'view_recommended_routes_title': 'عرض المسارات المقترحة',
      'view_recommended_routes_subtitle': 'شاهد كروت المسارات المرتبة وإرشادات الذكاء الاصطناعي.',
      'open_ai_assistant_title': 'فتح مساعد الذكاء الاصطناعي',
      'open_ai_assistant_subtitle': 'اسأل عن الأجرة، التوقيت، أو الربط بين المحطات.',
      'select_governorate': 'المحافظة',
      'select_city': 'المدينة / المنطقة',
      'select_destination_in_benha': 'أين تريد الذهاب في بنها؟',
      'popular_zones_sheet_title': 'اختر وجهتك في بنها',
      'train_route_first': 'مسار يعتمد على القطار أولاً',
      'train_route_connector': 'قطار + ميكروباص وصلة',
      'train_segment_detail': 'رحلة بالقطار من %s إلى %s مع ميكروباص وصلة إذا لزم الأمر.',
      'combined_train_route': 'مسار قطار مشترك',
      'combined_train_detail': 'استقل القطار من %s إلى رمسيس بالقاهرة، ثم انتقل إلى قطار بنها.',
      'no_routes_available': 'لا توجد مسارات متاحة',
      'try_adjusting_filters': 'حاول تعديل فلاتر البحث',
      'recommended': 'مقترح',
      'view_details': 'عرض التفاصيل ←',
      'duration': 'المدة',
      'cost': 'التكلفة',
      'cost_2026': 'التكلفة (تعريفة 2026)',
      'transfers': 'التحويلات',
      'route_plan': 'خطة السير',
      'min': 'دقيقة',
      'egp': 'جنيه',
      'transfer': 'تحويلة',
      'transfers_plural': 'تحويلات',
      'your_journey': 'رحلتك',
      'step_by_step_guidance': 'إرشادات خطوة بخطوة',
      'detailed_instructions_fallback': 'ستتوفر الإرشادات التفصيلية في التطبيق.',
      'rating_feedback': 'التقييم والآراء',
      'average_user_rating': 'متوسط تقييم المستخدمين',
      'price_estimate_disclaimer': '* الأسعار تقديرية بناءً على تعريفة عام 2026 وقد تختلف',
      'view_on_google_maps': 'عرض على خرائط جوجل',
      'back_to_results': 'العودة للنتائج',
      'sort_and_filter': 'الترتيب والتصفية',
      'cheapest': 'الأرخص',
      'fastest': 'الأسرع',
      'all_modes': 'كل الوسائل',
      'microbus': 'ميكروباص',
      'train': 'قطار',
      'public_bus': 'أتوبيس عام',
      'border_bus': 'حافلة حدودية',
      'transfer_point': 'نقطة التحويل/الانتقال',
      'type_university': 'جامعة',
      'type_hospital': 'مستشفى',
      'type_station': 'محطة',
      'type_hub': 'موقف / محطة رئيسية',
      'type_cafe': 'مقهى',
      'type_restaurant': 'مطعم',
      'sign_out_title': 'تسجيل الخروج',
      'sign_out_confirm': 'هل أنت متأكد من تسجيل الخروج؟',
      'cancel': 'إلغاء',
      'sign_out': 'تسجيل الخروج',
      'available_trains': 'القطارات المتاحة إلى بنها',
      'train_no': 'رقم القطار',
      'train_type': 'النوع',
      'departure': 'القيام',
      'arrival': 'الوصول لبنها',
      'price': 'السعر',
      'view_train_schedule': 'عرض جدول القطارات المتاحة',
    },
  };

  static const Map<String, String> _locationTranslations = {
    // Governorates
    'Cairo': 'القاهرة',
    'Giza': 'الجيزة',
    'Qalyubia': 'القليوبية',
    'Alexandria': 'الإسكندرية',
    'Gharbia': 'الغربية',
    'Dakahlia': 'الدقهلية',
    'Menofia': 'المنوفية',
    'Sharqia': 'الشرقية',
    'Beheira': 'البحيرة',
    'Kafr El Sheikh': 'كفر الشيخ',
    'Damietta': 'دمياط',
    'Port Said': 'بورسعيد',
    'Ismailia': 'الإسماعيلية',
    'Suez': 'السويس',
    'North Sinai': 'شمال سيناء',
    'South Sinai': 'جنوب سيناء',
    'Beni Suef': 'بني سويف',
    'Faiyum': 'الفيوم',
    'Minya': 'المنيا',
    'Asyut': 'أسيوط',
    'Sohag': 'سوهاج',
    'Qena': 'قنا',
    'Luxor': 'الأقصر',
    'Aswan': 'أسوان',
    'Red Sea': 'البحر الأحمر',
    'New Valley': 'الوادي الجديد',
    'Matrouh': 'مطروح',

    // Cairo Cities
    'Ahmed Helmy': 'أحمد حلمي',
    'El-Salam': 'السلام',
    'El-Marg': 'المرج',
    'Shubra El-Maza': 'شبرا المظلات / المؤسسة',
    'Helwan': 'حلوان',

    // Giza Cities
    'El-Haram': 'الهرم',
    'Imbaba': 'إمبابة',
    '6th of October': '6 أكتوبر',
    'El-Warraq': 'الوراق',
    'Dokki': 'الدقي',

    // Qalyubia Cities
    'Benha': 'بنها',
    'Qaha': 'قها',
    'Toukh': 'طوخ',
    'Shibin Al Qanater': 'شبين القناطر',
    'Kafr Shukr': 'كفر شكر',
    'Qalyub': 'قليوب',
    'Khanka': 'الخانكة',
    'Al-Obour': 'العبور',
    'Shubra Al-Khaimah': 'شبرا الخيمة',
    'Qanater Al-Khayria': 'القناطر الخيرية',

    // Menofia Cities
    'Shibin El-Kom': 'شبين الكوم',
    'Ashmoun': 'أشمون',
    'Menouf': 'منوف',
    'Sars El-Lyan': 'سرس الليان',
    'Quweisna': 'قويسنا',
    'El-Bagour': 'الباجور',

    // Gharbia Cities
    'Tanta': 'طنطا',
    'Mahalla': 'المحلة الكبرى',
    'Kafr El-Zayat': 'كفر الزيات',

    // Dakahlia Cities
    'Mansoura': 'المنصورة',
    'Mit Ghamr': 'ميت غمر',
    'Aga': 'أجا',
    'Talkha': 'طلخا',

    // Kafr El Sheikh Cities
    'Kafr El Sheikh City': 'كفر الشيخ',
    'Sidi Salem': 'سيدي سالم',

    // Other Cities
    'Alexandria City': 'الإسكندرية',
    'Zagazig': 'الزقازيق',
    'Damanhour': 'دمنهور',
    'Damietta City': 'دمياط',
    'Port Said City': 'بورسعيد',
    'Ismailia City': 'الإسماعيلية',
    'Suez City': 'السويس',
    'Fayoum City': 'الفيوم',
    'Beni Suef City': 'بني سويف',
    'Minya City': 'المنيا',
    'Asyut City': 'أسيوط',
    'Sohag City': 'سوهاج',
    'Qena City': 'قنا',
    'Luxor City': 'الأقصر',
    'Aswan City': 'أسوان',
    'Hurghada': 'الغردقة',
    'Kharga': 'الخارجة',
    'Marsa Matrouh': 'مرسى مطروح',
    'Arish': 'العريش',
    'Tor': 'الطور',

    // Benha Destinations
    'Benha Main Bus Terminal': 'موقف بنها',
    'Benha Train Station': 'محطة قطار بنها',
    'Faculty of Engineering': 'كلية الهندسة',
    'Faculty of Medicine': 'كلية الطب',
    'Faculty of Science': 'كلية العلوم',
    'Faculty of Commerce': 'كلية التجارة',
    'Faculty of Arts': 'كلية الآداب',
    'Faculty of Agriculture': 'كلية الزراعة بمشتهر',
    'Faculty of Education': 'كلية التربية',
    'Faculty of Applied Arts': 'كلية الفنون التطبيقية',
    'Faculty of Nursing': 'كلية التمريض',
    'Faculty of Computers and AI': 'كلية الحاسبات والذكاء الاصطناعي',
    'Benha University Hospital': 'مستشفى بنها الجامعي',
    'Al-Ahram Street': 'شارع الأهرام (وسط البلد)',
    'Kafr El-Gazzar': 'كفر الجزار',

    'Colleges Complex (Commerce - Arts)': 'مجمع الكليات (كلية تجارة - كلية اداب)',
    'University Administration': 'إدارة الجامعة',
    'Medicine, Hospital & Corniche (El-Eshara)': 'كلية طب ومستشفى الجامعة وكورنيش النيل (إشارة)',
    'Al-Ahram Area': 'منطقة الأهرام',
    'Old Benha Bridge': 'كوبري (بنها القديمة)',
    'Faculty of Law': 'كلية الحقوق',
    'University Dorms': 'المدينة الجامعية',
    'Al-Villas Area': 'منطقة الفلل',
    'Colleges Complex': 'مجمع الكليات',
    'Administration': 'إدارة الجامعة',
    'Hospital & Corniche': 'المستشفى والكورنيش',
    'Al-Ahram': 'الأهرام',
    'Old Bridge': 'الكوبري القديم',
    'Law': 'كلية الحقوق',
    'Dorms': 'المدينة الجامعية',
    'Villas': 'منطقة الفلل',

    // New Representative Stations
    'Helwan University': 'جامعة حلوان',
    'Maadi': 'المعادي',
    'Sayeda Zeinab': 'السيدة زينب',
    'Hadayek El-Kobba': 'حدائق القبة',
    'El-Marg El-Jedida': 'المرج الجديدة',
    'Faculty of Agriculture Metro': 'كلية الزراعة (المترو)',
    'Cairo University': 'جامعة القاهرة',
    'El-Mounib': 'المنيب',
    'Nadi El-Shams': 'نادي الشمس',
    'Abassia': 'العباسية',
    'Kit Kat': 'الكيت كات',
    'Rod El-Farag Axis': 'محور روض الفرج',
    'El-Shorouk': 'الشروق',
    'Badr City': 'بدر',
    '10th of October LRT': 'العاشر من رمضان',
    'Arts & Culture City': 'مدينة الفنون والثقافة',
    'El-Estad Monorail': 'الإستاد (المونوريل)',
    'Fifth Settlement': 'التجمع الخامس',
    'AUC Station': 'الجامعة الأمريكية',
    'Governmental District': 'الحي الحكومي',
    'Wadi El-Nile Monorail': 'وادي النيل',
    'Hyper One': 'هايبر ون',
    'El-Hosary Monorail': 'الحصري',
    'Bashtiel Station': 'قطار الصعيد (بشتيل)',
    
    'Sadat Metro': 'السادات (المترو)',
    'Nasser Metro': 'ناصر (المترو)',
    'Attaba Metro': 'العتبة (المترو)',
    'Al-Shohadaa Metro': 'الشهداء (المترو)',
    'El-Mazallat Metro': 'المظلات (المترو)',
    'Rod El-Farag Metro': 'روض الفرج (المترو)',
    'Massarra Metro': 'مسرة (المترو)',
    'Mohamed Naguib Metro': 'محمد نجيب (المترو)',
    'Opera Metro': 'الأوبرا (المترو)',
    'El-Bohouth Metro': 'البحوث (المترو)',
    'League of Arab States Metro': 'جامعة الدول (المترو)',
    'Boulaq El-Dakrour Metro': 'بولاق الدكرور (المترو)',
  };

  String translateLocation(String name) {
    if (locale.languageCode == 'ar') {
      return _locationTranslations[name] ?? name;
    }
    return name;
  }

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
